baseURL = 'https://manicmoth.github.io/'
languageCode = 'en-us'
title = 'Moth'



theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
