baseURL = 'https://midyear.moth.ooo/'
languageCode = 'en-us'
title = 'Moth'
publishDir = "docs"


theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
